//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidateMassages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidateMassages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Service.Resources.ValidateMassages", typeof(ValidateMassages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors information is requared..
        /// </summary>
        internal static string BookAuthorsRequared {
            get {
                return ResourceManager.GetString("BookAuthorsRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN is requared..
        /// </summary>
        internal static string BookISBNRequared {
            get {
                return ResourceManager.GetString("BookISBNRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count page is requared..
        /// </summary>
        internal static string CountPageRequared {
            get {
                return ResourceManager.GetString("CountPageRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is requared..
        /// </summary>
        internal static string NameRequared {
            get {
                return ResourceManager.GetString("NameRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISSN is requared..
        /// </summary>
        internal static string NewspaperISSNRequared {
            get {
                return ResourceManager.GetString("NewspaperISSNRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newspaper number is requared..
        /// </summary>
        internal static string NewspaperNumberRequared {
            get {
                return ResourceManager.GetString("NewspaperNumberRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact has unknown type..
        /// </summary>
        internal static string NotLibraryArtifact {
            get {
                return ResourceManager.GetString("NotLibraryArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent author is requared..
        /// </summary>
        internal static string PatentAuthorRequared {
            get {
                return ResourceManager.GetString("PatentAuthorRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent reqistration number is requared..
        /// </summary>
        internal static string PatentRegistrationNumberRequared {
            get {
                return ResourceManager.GetString("PatentRegistrationNumberRequared", resourceCulture);
            }
        }
    }
}
